// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQHfqN04s1AID68XObvmbISvZonuiIeoE',
    appId: '1:187972426079:web:ec78129f89c88714a17eea',
    messagingSenderId: '187972426079',
    projectId: 'brewit-4ceaf',
    authDomain: 'brewit-4ceaf.firebaseapp.com',
    storageBucket: 'brewit-4ceaf.appspot.com',
    measurementId: 'G-EZE7V9P1QQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAoRvOsDg_G9SRWusZaNX6LIsp0jWY9jo',
    appId: '1:187972426079:android:876f0c8a4046e48ba17eea',
    messagingSenderId: '187972426079',
    projectId: 'brewit-4ceaf',
    storageBucket: 'brewit-4ceaf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmXmiFvtxhk2xLOE7I5WRc9S-1y7j9eyg',
    appId: '1:187972426079:ios:1361f06a09bc237da17eea',
    messagingSenderId: '187972426079',
    projectId: 'brewit-4ceaf',
    storageBucket: 'brewit-4ceaf.appspot.com',
    iosClientId: '187972426079-n3cjcm553eult2f6umoi888olk5u3ehk.apps.googleusercontent.com',
    iosBundleId: 'com.andyleeboo.brewit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmXmiFvtxhk2xLOE7I5WRc9S-1y7j9eyg',
    appId: '1:187972426079:ios:847cef72c1eaba2da17eea',
    messagingSenderId: '187972426079',
    projectId: 'brewit-4ceaf',
    storageBucket: 'brewit-4ceaf.appspot.com',
    iosClientId: '187972426079-cq8onkem1sf96mm71qopr6vfsc1v4v5u.apps.googleusercontent.com',
    iosBundleId: 'com.andyleeboo.brewit.RunnerTests',
  );
}
